version: "3"
services:
  # Node.js + Express Backend
  backend:
    image: node:alpine3.17
    container_name: backend
    working_dir: /app
    command: npm run dev
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app
      - ./profilepics:/profilepics
    environment:
      - NODE_ENV=dev
    depends_on:
      - database

  # PostgreSQL
  database:
    hostname: database
    image: postgres:14
    container_name: postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d # Mount directory for initial SQL files

  # React.js Frontend
  frontend:
    image: node:alpine3.17
    container_name: frontend
    working_dir: /app
    command: npm start
    volumes:
      - ./frontend:/app
      - ./profilepics:/app/public/profilepics
    ports:
      - "3000:3000"
